# Generated by Django 4.2.16 on 2024-10-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AesKeyEncWithAbe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_serial', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('authority_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('HEALTH_CLUB', 'Health Club'), ('INSURANCE_COMPANY', 'Insurance Company'), ('WORK_COMPANY', 'Work Company')], max_length=20)),
                ('attributes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityRep',
            fields=[
                ('rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rep_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('INSURANCE_REP', 'Insurance Representative'), ('WORK_REP', 'Employer'), ('HEALTH_CLUB_REP', 'Health Club Representative')], max_length=25)),
                ('attributes', models.JSONField(default=list)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authority')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attributes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PubKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('egga_serial', models.BinaryField()),
                ('gy_serial', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='SecKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alpha_serial', models.BinaryField()),
                ('y_serial', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50, unique=True)),
                ('attributes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authorityrep')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('aes_enc_message', models.BinaryField()),
                ('message_type', models.CharField(choices=[('HEALTH', 'Health'), ('TRAINING', 'Training')], max_length=10)),
                ('aes_key_enc_with_abe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aeskeyencwithabe')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.AddField(
            model_name='authority',
            name='pub_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.pubkey'),
        ),
        migrations.AddField(
            model_name='authority',
            name='sec_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.seckey'),
        ),
    ]
