# Generated by Django 4.2.16 on 2024-11-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AesKeyEncWithAbe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_serial', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityRep',
            fields=[
                ('rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attributes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MAABEPublicParams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g1_serial', models.BinaryField()),
                ('g2_serial', models.BinaryField()),
                ('egg_serial', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attributes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PubKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('egga_serial', models.BinaryField()),
                ('gy_serial', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='SecKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alpha_serial', models.BinaryField()),
                ('y_serial', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authorityrep')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('aes_enc_message', models.BinaryField()),
                ('message_type', models.CharField(choices=[('HEALTH', 'Health'), ('TRAINING', 'Training')], max_length=10)),
                ('aes_key_enc_with_abe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aeskeyencwithabe')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attributes', models.JSONField(default=list)),
                ('pub_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.pubkey')),
                ('sec_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.seckey')),
            ],
        ),
    ]
