# Generated by Django 4.2.16 on 2024-10-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAABEPublicParams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g1_serial', models.BinaryField()),
                ('g2_serial', models.BinaryField()),
                ('egg_serial', models.BinaryField()),
            ],
        ),
    ]
