# Generated by Django 4.2.16 on 2024-11-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_maabepublicparams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='authority_type',
        ),
        migrations.RemoveField(
            model_name='authorityrep',
            name='rep_type',
        ),
        migrations.AlterField(
            model_name='authority',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authorityrep',
            name='rep_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
